### PR TITLE
add avg topic size and fix bug

### PR DESCRIPTION
**Pull request by Cczzzz**
#63 
add avg topic size
fix bug java.io.CharConversionException: Not an ISO 8859-1 character:
fix correct unit for remainHowManyDataToFlush

### CODE REVIEW

**Comment by maixiaohai** [comment]
@Cczzzz one pr only fix one thing, pls split the pr to make it clearly and more maintainable.

**Comment by maixiaohai** [comment]
ping~

**Comment by ShannonDing** [comment]
ping @Cczzzz , i fix the file conflicts first. pls check and split the avg topic size feature and bug fix code to different PRs.

**Review by ShannonDing — CHANGES_REQUESTED** [review]
ping @Cczzzz , i fix the file conflicts first. pls check and split the avg topic size feature and bug fix code to different PRs.

**Comment by francisoliverlee** [comment]
i will close this PR cause of conflict, and feel free to reopen it

**Pull request closed without merging**
